module.exports = {
  plugins: ['node'],
  rules: {
    'node/callback-return': 0,
    'node/exports-style': [2, 'module.exports'],
    'node/file-extension-in-import': [2, 'never'],
    'node/global-require': 2,
    'node/handle-callback-err': 0,
    'node/no-callback-literal': 0,
    'node/no-deprecated-api': 2,
    'node/no-exports-assign': 2,
    'node/no-extraneous-import': 2,
    'node/no-extraneous-require': 2,
    'node/no-missing-import': 2,
    'node/no-missing-require': 2,
    'node/no-mixed-requires': 2,
    'node/no-new-require': 2,
    'node/no-path-concat': 0,
    'node/no-process-env': 0,
    'node/no-process-exit': 0,
    'node/no-restricted-import': 0,
    'node/no-restricted-require': 0,
    'node/no-sync': 0,
    'node/no-unpublished-bin': 0,
    'node/no-unpublished-import': 0,
    'node/no-unpublished-require': 0,
    'node/no-unsupported-features/es-builtins': 2,
    'node/no-unsupported-features/es-syntax': 2,
    'node/no-unsupported-features/node-builtins': 2,
    'node/prefer-global/buffer': [2, 'never'],
    'node/prefer-global/console': [2, 'always'],
    'node/prefer-global/process': [2, 'always'],
    'node/prefer-global/text-decoder': [2, 'never'],
    'node/prefer-global/text-encoder': [2, 'never'],
    'node/prefer-global/url-search-params': [2, 'never'],
    'node/prefer-global/url': [2, 'never'],
    'node/prefer-promises/dns': 0,
    'node/prefer-promises/fs': 0,
    'node/process-exit-as-throw': 2,
    'node/shebang': 2
  }
}
