module.exports = {
  rules: {
    'accessor-pairs': 2,
    'array-callback-return': [2, { checkForEach: true }],
    'block-scoped-var': 2,
    'class-methods-use-this': 2,
    complexity: [2, 10],
    'consistent-return': 2,
    curly: [2, 'multi-line'],
    'default-case': 2,
    'default-case-last': 2,
    'default-param-last': 2,
    'dot-location': [2, 'property'],
    'dot-notation': [2, { allowKeywords: true }],
    eqeqeq: [2, 'always', { null: 'ignore' }],
    'grouped-accessor-pairs': 2,
    'guard-for-in': 2,
    'max-classes-per-file': 1,
    'no-alert': 2,
    'no-caller': 2,
    'no-case-declarations': 2,
    'no-constructor-return': 2,
    'no-div-regex': 2,
    'no-else-return': 2,
    'no-self-assign': [2, { props: true }],
    'no-empty-function': 1,
    'no-empty-pattern': 2,
    'no-eq-null': 2,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-extra-label': 2,
    'no-fallthrough': 2,
    'no-floating-decimal': 2,
    'no-global-assign': 2,
    'no-implicit-coercion': 0,
    'no-implicit-globals': [2, { lexicalBindings: true }],
    'no-implied-eval': 2,
    'no-invalid-this': 2,
    'no-iterator': 2,
    'no-labels': 2,
    'no-lone-blocks': 2,
    'no-loop-func': 2,
    'no-magic-numbers': 0,
    'no-multi-spaces': 2,
    'no-multi-str': 2,
    'no-new': 2,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-octal': 2,
    'no-octal-escape': 2,
    'no-param-reassign': 2,
    'no-proto': 2,
    'no-redeclare': [2, { builtinGlobals: false }],
    'no-restricted-properties': 0,
    'no-return-assign': [2, 'except-parens'],
    'no-return-await': 2,
    'no-script-url': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-throw-literal': 2,
    'no-unmodified-loop-condition': 2,
    'no-unused-expressions': [2, {
      allowTaggedTemplates: true,
      allowShortCircuit: true,
      allowTernary: true
    }],
    'no-unused-labels': 2,
    'no-useless-call': 2,
    'no-useless-catch': 2,
    'no-useless-concat': 2,
    'no-useless-escape': 2,
    'no-useless-return': 2,
    'no-void': 2,
    'no-warning-comments': 0,
    'no-with': 2,
    'prefer-named-capture-group': 0,
    'prefer-promise-reject-errors': 2,
    'prefer-regex-literals': 2,
    radix: 2,
    'require-await': 2,
    'require-unicode-regexp': 2,
    'vars-on-top': 0,
    'wrap-iife': [2, 'any', { functionPrototypeMethods: true }],
    yoda: [2, 'never']
  }
}
