module.exports = {
  plugins: ['unicorn'],
  rules: {
    'unicorn/better-regex': 0,
    'unicorn/catch-error-name': [2, { ignore: ['^e$', '^err'] }],
    'unicorn/consistent-function-scoping': 2,
    'unicorn/custom-error-definition': 2,
    'unicorn/error-message': 2,
    'unicorn/escape-case': 1,
    'unicorn/expiring-todo-comments': 0,
    'unicorn/explicit-length-check': 2,
    'unicorn/filename-case': [2, { case: 'snakeCase' }],
    'unicorn/import-index': 0,
    'unicorn/new-for-builtins': 2,
    'unicorn/no-abusive-eslint-disable': 2,
    'unicorn/no-array-instanceof': 2,
    'unicorn/no-console-spaces': 2,
    'unicorn/no-fn-reference-in-iterator': 0,
    'unicorn/no-for-loop': 0,
    'unicorn/no-hex-escape': 2,
    'unicorn/no-keyword-prefix': 0,
    'unicorn/no-nested-ternary': 0,
    'unicorn/no-new-buffer': 2,
    'unicorn/no-null': 0,
    'unicorn/no-process-exit': 0,
    'unicorn/no-reduce': 0,
    'unicorn/no-unreadable-array-destructuring': 0,
    'unicorn/no-unsafe-regex': 2,
    'unicorn/no-unused-properties': 0,
    'unicorn/no-useless-undefined': 2,
    'unicorn/no-zero-fractions': 0,
    'unicorn/number-literal-case': 2,
    'unicorn/prefer-add-event-listener': 0,
    'unicorn/prefer-dataset': 0,
    'unicorn/prefer-event-key': 0,
    'unicorn/prefer-flat-map': 2,
    'unicorn/prefer-includes': 2,
    'unicorn/prefer-modern-dom-apis': 0,
    'unicorn/prefer-negative-index': 2,
    'unicorn/prefer-node-append': 2,
    'unicorn/prefer-node-remove': 0,
    'unicorn/prefer-number-properties': 2,
    'unicorn/prefer-optional-catch-binding': 0,
    'unicorn/prefer-query-selector': 2,
    'unicorn/prefer-reflect-apply': 0,
    'unicorn/prefer-replace-all': 0,
    'unicorn/prefer-set-has': 0,
    'unicorn/prefer-spread': 2,
    'unicorn/prefer-starts-ends-with': 2,
    'unicorn/prefer-string-slice': 2,
    'unicorn/prefer-text-content': 2,
    'unicorn/prefer-trim-start-end': 0,
    'unicorn/prefer-type-error': 2,
    'unicorn/prevent-abbreviations': 0,
    'unicorn/string-content': 0,
    'unicorn/throw-new-error': 2
  }
}
