module.exports = {
  plugins: ['clean-regex'],
  rules: {
    'clean-regex/confusing-quantifier': 1,
    'clean-regex/consistent-match-all-characters': [1, { mode: 'dot' }],
    'clean-regex/no-constant-capturing-group': 2,
    'clean-regex/no-empty-backreference': 2,
    'clean-regex/no-empty-lookaround': 2,
    'clean-regex/no-lazy-ends': 2,
    'clean-regex/no-lone-square-bracket': 2,
    'clean-regex/no-octal-escape': 1,
    'clean-regex/no-optional-assertion': 0,
    'clean-regex/no-potentially-empty-backreference': 1,
    'clean-regex/no-trivially-nested-lookaround': 1,
    'clean-regex/no-unnecessary-assertions': 2,
    'clean-regex/no-unnecessary-character-class': 2,
    'clean-regex/no-unnecessary-flag': 2,
    'clean-regex/no-unnecessary-group': 2,
    'clean-regex/no-unnecessary-lazy': 2,
    'clean-regex/no-unnecessary-quantifier': 2,
    'clean-regex/no-zero-quantifier': 2,
    'clean-regex/optimal-concatenation-quantifier': 1,
    'clean-regex/optimal-lookaround-quantifier': 1,
    'clean-regex/optimized-character-class': 2,
    'clean-regex/prefer-character-class': 2,
    'clean-regex/prefer-predefined-character-set': 1,
    'clean-regex/prefer-predefined-quantifiers': 2,
    'clean-regex/simple-constant-quantifier': 2,
    'clean-regex/sort-flags': 2
  }
}
