module.exports = {
  plugins: ['lodash'],
  rules: {
    'lodash/callback-binding': 2,
    'lodash/chain-style': [1, 'explicit'],
    'lodash/chaining': [2, 'never'],
    'lodash/collection-method-value': 1,
    'lodash/collection-ordering': 0,
    'lodash/collection-return': 2,
    'lodash/consistent-compose': 0,
    'lodash/identity-shorthand': 0,
    'lodash/import-scope': [2, 'method'],
    'lodash/matches-prop-shorthand': 0,
    'lodash/matches-shorthand': 0,
    'lodash/no-commit': 0,
    'lodash/no-double-unwrap': 2,
    'lodash/no-extra-args': 2,
    'lodash/no-unbound-this': 2,
    'lodash/path-style': [2, 'string'],
    'lodash/prefer-compact': 0,
    'lodash/prefer-constant': 0,
    'lodash/prefer-filter': 0,
    'lodash/prefer-find': 0,
    'lodash/prefer-flat-map': 0,
    'lodash/prefer-get': 2,
    'lodash/prefer-immutable-method': 1,
    'lodash/prefer-includes': 2,
    'lodash/prefer-invoke-map': 2,
    'lodash/prefer-is-nil': 2,
    'lodash/prefer-lodash-chain': 0,
    'lodash/prefer-lodash-method': 0,
    'lodash/prefer-lodash-typecheck': 2,
    'lodash/prefer-map': 0,
    'lodash/prefer-matches': 2,
    'lodash/prefer-noop': 2,
    'lodash/prefer-over-quantifier': 0,
    'lodash/prefer-reject': 0,
    'lodash/prefer-some': 0,
    'lodash/prefer-startswith': 2,
    'lodash/prefer-thru': 0,
    'lodash/prefer-times': 2,
    'lodash/prefer-wrapper-method': 0,
    'lodash/preferred-alias': 0,
    'lodash/prop-shorthand': 0,
    'lodash/unwrap': 0
  }
}
